spring:
  application:
    name: mailmonkeyai-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/mailmonkey_db
    username: postgres
    password: pass123
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_EXPIRATION_MS}
  refresh-token-expiration-ms: ${JWT_REFRESH_MS}

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}

frontend:
  url: ${FRONTEND_URL}
